name: Generate GitHub Profile Cards

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cards:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate profile summary SVG
        uses: vn7n24fzkq/github-profile-summary-cards@latest
        with:
          USERNAME: matan2288
          OUTPUT: summary.svg

      - name: Commit SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add summary.svg
          git commit -m "update profile summary" || exit 0
          git push
